export const Themes = {
    light: {
        background: "#FFFFFF",
        primaryText: "#000000",
        secondaryText: "#6A6A6A",
        accent: "#D32F2F",
        border: "#B0B0B0",
        headerBackground: "#F5F5F5",
        linkText: "#1E90FF",
        errorText: "#D32F2F",
        fontSizes: {
            small: 12,
            medium: 14,
            large: 18,
            xlarge: 22,
        },
        fontWeights: {
            normal: "400",
            bold: "700",
        },
    },
    dark: {
        background: "#121212",
        primaryText: "#FFFFFF",
        secondaryText: "#B3B3B3",
        accent: "#FF5252",
        border: "#424242",
        headerBackground: "#1E1E1E",
        linkText: "#1E90FF",
        errorText: "#FF5252",
        fontSizes: {
            small: 12,
            medium: 14,
            large: 18,
            xlarge: 22,
        },
        fontWeights: {
            normal: "400",
            bold: "700",
        },
    },
    grandma: {
        background: "#FDF5E6",
        primaryText: "#000000",
        secondaryText: "#4B4B4B",
        accent: "#FF69B4",
        border: "#D3D3D3", 
        headerBackground: "#FFE4B5", 
        linkText: "#0000EE", 
        errorText: "#FF4500",
        fontSizes: {
            small: 16,
            medium: 18,
            large: 22,
            xlarge: 26,
        },
        fontWeights: {
            normal: "400",
            bold: "700",
        },
    },
};